### ISSUE TITLE
Printing Arabic with English

### ISSUE THREAD

**Issue by joesalloum** [auctifera-josed/starprnt#16]
is there any documentation or anyone can help on how to use both arabic, english and barcode in same print ?

thank you

**Comment by infoxicator** [comment]
Hi, @joesalloum I had a look at the official Demo application included with the StarSDK, but I can't find any examples of how to print Arabic. The only examples provided are 

'US-ASCII' | English
'Windows-1252' | French, German, Portuguese, Spanish
'Shift-JIS' | Japanese
'Windows-1251' | Russian
'GB2312' | Simplified Chinese
'Big5' | Traditional Chinese
'UTF-8' | UFT8

Your best bet is to try UTF-8 or any other encoding, combined with Code Page type i.e  CP864. You can send bytes to the printer representing your characters this way. See how to print the pound £ or Euro sign for usage

**Comment by joesalloum** [comment]
please in the {appendBytes:[0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x20, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x2e]}

working as charm but i need to fill the array dynamically from webservice i'm returning an array of strings and it's not working it has to be without the quotes

```
["0x6A", "0x61", "0x64"] doesn't work
[0x6A, 0x61, 0x64] works
```

i need one of the fixes or to allow the appendBytes to work with strings
or to allow the appendRaw to work as the appendBytes when using arabic hex code

**Comment by infoxicator** [comment]
Hi @joesalloum, I am afraid that the printer only takes Integers (Numbers 0x6A, 0x61, 0x64) if you send them as strings, the printCommand function thinks you want to print "0x61" instead of the charachter that it represents. You can create a function that loops through the items in your array that you received throgh webservices and then parse them to number.
